### ISSUE TITLE
Error CodePush Android 'undefined is not a function This error is located at: in App in CodePushComponent in RCTView in Unknown in RCTView in Unknown in AppContainer'

### ISSUE THREAD

**Issue by renan-5by5** [microsoft/react-native-code-push#2228]
Hello, I'm getting a lot of crashes in my Crashlytics with the below error:

h.g.p.z.c
h.g.p.z.c: TypeError: undefined is not a function This error is located at: in App in CodePushComponent in RCTView in Unknown in RCTView in Unknown in AppContainer, js engine: hermes, stack: componentWillUnmount@1:615510 commitUnmount@1:142918 unmountHostComponents@1:144883 commitMutationEffects@1:146131 commitRootImpl@1:153297 commitRoot@1:152915 performSyncWorkOnRoot@1:149960 flushSyncCallbacks@1:117889 scheduleUpdateOnFiber@1:147810 enqueueSetState@1:161773 anonymous@1:275972 _callee23$@1:614020 tryCatch@1:87105 invoke@1:88111 anonymous@1:87253 tryCatch@1:87105 invoke@1:87338 anonymous@1:87552 tryCallOne@53:15 anonymous@139:26 anonymous@1:191764 _callTimer@1:190707 _callReactNativeMicrotasksPass@1:190913 callReactNativeMicrotasks@1:192839 __callReactNativeMicrotasks@1:180692 anonymous@1:179824 __guard@1:180569 flushedQueue@1:179735 invokeCallbackAndReturnFlushedQueue@1:179678 (#fc8bacdb4bc3212f)

I couldn't find anything on the internet talking about this error and we did numerous tests but we couldn't simulate any similar error. This is happening a lot in production, 10% of customers are having this error.

Note: This started happening after we updated the react-native version 0.63.4 to 0.67.1.

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.67.1
* react version: 17.0.2

**Comment by kwangjaeyoo** [comment]
I have Same issus in m1 mac(12.1) ( not show intel mac 11.4 )

updated react version 0.64. to 0.66.4

**Comment by ivosabev** [comment]
+1

**Comment by raghava-409** [comment]
@renan-5by5 Were you able find the cause and solve for this?
I am facing the same when upgraded RN to 0.72.3 and codepush to 8.0.2
