### ISSUE TITLE
Unable to build debug ios React Native 0.59.1

### ISSUE THREAD

**Issue by acollazomayer** [Microsoft/react-native-code-push#1544]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Upgrade from version 0.58.6 to 0.59.1

### Expected Behavior
To buid ios
### Actual Behavior
Build is failing
```
  ** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze /node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
	Analyze Base/RCTModuleMethod.mm normal x86_64
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /ios/build/App/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePush.o /node_modules/react-native-code-push/ios/CodePush/CodePush.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.5.3
* react-native version: 0.59.1
* iOS/Android/Windows version: ios 12
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by alexandergoncharov** [comment]
Hi @acollazomayer ,
Thanks for reporting!

Unfortunately I can't reproduce it as 59 version works correct with CodePush plugin. Possible there is some issue with upgrading your project. Could you please share some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by acollazomayer** [comment]
@alexandergoncharov I can not give you the dummy project. However, I had the last version of codepush installed in a 0.58.6 react native app. After I upgraded using this changelogs https://github.com/react-native-community/rn-diff-purge/compare/version/0.58.6...version/0.59.0

When I build the project was not building anymore.

**Comment by alexandergoncharov** [comment]
oh, I see. Could you please try to upgrade also `react-native-code-push` plugin?

**Comment by acollazomayer** [comment]
@alexandergoncharov I've tried that with no luck

**Comment by anshumanburman** [comment]
I am also facing same issue. i am still not able to run the app. my react native info below

React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 160.39 MB / 10.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.1, 28.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react-native: 0.59.0 => 0.59.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by anshumanburman** [comment]
Now it is working fine in 0.59.1 on mac .

**Comment by alexandergoncharov** [comment]
Hi @anshumanburman, Thanks for letting us know!

@acollazomayer, could you please try to use 0.59.1 or 0.59.2? If this will not help could you please provide some dummy project with reproducing issue and reprosteps?  would like to debug it.

Thanks,
Alexander

**Comment by acollazomayer** [comment]
@alexandergoncharov Hi alexander sorry for the late response, I will sure try, but right now I am busy. Whenever i have the time I will do it.

**Comment by alexandergoncharov** [comment]
Hi @acollazomayer , just a friendly ping :)

**Comment by acollazomayer** [comment]
@alexandergoncharov yeah I know. Im finishing a huge refactor and my next task is to upgrade to 0.59 version so in a few days I will tell you more

**Comment by alexandergoncharov** [comment]
Hi @acollazomayer , just a friendly ping :)

**Comment by yuri-kulikov** [comment]
Hi @acollazomayer,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or new details!

**Comment by pilot4u** [comment]
I'm having similar issue and cannot build our iOS project, receiving following exception:
`/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:11:17: error: 
      declaration of 'RCTConvert' must be imported from module 'React' before it is
      required
@implementation RCTConvert (CodePushInstallMode)
                ^
In module 'React' imported from /Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/CodePush.h:2:
/Users/newtrina/Develop/newtrina-chef-react-native/ios/Pods/Headers/Public/React/React/RCTConvert.h:27:16: note: 
      previous declaration is here
    @interface RCTConvert : NSObject
               ^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:13:42: error: 
      expected ')'
RCT_ENUM_CONVERTER(CodePushInstallMode, (@{ @"codePushInstallModeImmediate": @(C...
                                         ^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:13:41: note: 
      to match this '('
RCT_ENUM_CONVERTER(CodePushInstallMode, (@{ @"codePushInstallModeImmediate": @(C...
                                        ^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:13:42: warning: 
      type specifier missing, defaults to 'int' [-Wimplicit-int]
RCT_ENUM_CONVERTER(CodePushInstallMode, (@{ @"codePushInstallModeImmediate": @(C...
                                         ^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:17:20: warning: 
      type specifier missing, defaults to 'int' [-Wimplicit-int]
                   CodePushInstallModeImmediate, // Default enum value
                   ^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:18:20: warning: 
      type specifier missing, defaults to 'int' [-Wimplicit-int]
                   integerValue)
                   ^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:20:1: error: 
      expected function body after function declarator
@end
^
/Users/newtrina/Develop/newtrina-chef-react-native/node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushInstallMode.m:20:5: error: 
      missing '@end'
@end
    ^`
### Environment

* react-native-code-push version: 5.6.1
* react-native version: 0.59.1
* iOS/Android/Windows version: macos 10.13.6
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? physical
