### ISSUE TITLE
error: cannot find symbol 'isLiveReloadEnabled = devInternalSettings' after upgrading RN to v0.63.3

### ISSUE THREAD

**Issue by vorousjames** [microsoft/react-native-code-push#1979]
### Steps to Reproduce
1. I upgraded my project manually following the rn upgrade helper from 0.61.5 to 0.63.3
2. pulled from my private repo, which has a gitignore that was created based on [this](https://www.gitignore.io/api/reactnative)
3. I had react-native-code-push integrated already 
4. followed some additional code push for added build variants. the visual studio epicenter guide I followed is [here](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-deployment).

### Expected Behavior
I expected my app to have no issues building, running

### Actual Behavior
android sync successful.
clean successful.
build/compilation failure.

> Task :react-native-code-push:compileDebugJavaWithJavac FAILED
> /Users/Desktop/Development/App/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java:157: error: cannot find symbol
>                 isLiveReloadEnabled = devInternalSettings.isReloadOnJSChangeEnabled();
>                                                          ^
>   symbol:   method isReloadOnJSChangeEnabled()
>   location: variable devInternalSettings of type DevInternalSettings
> /Users/Desktop/Development/App/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:175: warning: [unchecked] unchecked cast
>         List<ReactRootView> mAttachedRootViews = (List<ReactRootView>)mAttachedRootViewsField.get(instanceManager);
>                                                                                                  ^
>   required: List<ReactRootView>
>   found:    Object
> 1 error
> 1 warning

### Environment

* react-native-code-push version: ^6.0.0
* react-native version: 0.63.3
* iOS/Android/Windows version:  compiledSDKVersion: 29
* Does this reproduce on a debug build or release build? whatever variant compiles after hitting run in android studio
* Does this reproduce on a simulator, or only on a physical device? simulator
