### ISSUE TITLE
Task :react-native-code-push:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by fanzhiri** [microsoft/react-native-code-push#2393]
### Environment

* react-native-code-push version:
* react-native version:0.60.5
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build?  both
* Does this reproduce on a simulator, or only on a physical device? can not success build 

(The more info the faster we will be able to address it!)

> Task :react-native-code-push:compileReleaseJavaWithJavac FAILED
Caching disabled for task ':react-native-code-push:compileReleaseJavaWithJavac' because:
  Build cache is disabled
Task ':react-native-code-push:compileReleaseJavaWithJavac' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':react-native-code-push:compileReleaseJavaWithJavac'.
Compiling with source level 1.7 and target level 1.7.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
file or directory 'D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\release\java', not found
file or directory 'D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\build\generated\aidl_source_output_dir\release\compileReleaseAidl\out', not found
file or directory 'D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\build\generated\renderscript_source_output_dir\release\compileReleaseRenderscript\out', not found
Compiling with JDK Java compiler API.
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:8: : com.facebook.react
import com.facebook.react.ReactInstanceManager;
                         ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:9: : com.facebook.react
import com.facebook.react.ReactPackage;
                         ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:10: : com.facebook.react.bridge
import com.facebook.react.bridge.JavaScriptModule;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:11: : com.facebook.react.bridge
import com.facebook.react.bridge.NativeModule;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:12: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:13: : com.facebook.react.devsupport
import com.facebook.react.devsupport.DevInternalSettings;
                                    ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:14: : com.facebook.react.devsupport.interfaces
import com.facebook.react.devsupport.interfaces.DevSupportManager;
                                               ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:15: : com.facebook.react.uimanager
import com.facebook.react.uimanager.ViewManager;
                                   ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:24: : Ҳ
public class CodePush implements ReactPackage {
                                 ^
  :  ReactPackage
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:6: : com.facebook.react.bridge
import com.facebook.react.bridge.Arguments;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:7: : com.facebook.react.bridge
import com.facebook.react.bridge.ReadableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:8: : com.facebook.react.bridge
import com.facebook.react.bridge.WritableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\ReactInstanceHolder.java:3: : com.facebook.react
import com.facebook.react.ReactInstanceManager;
                         ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:123: : Ҳ
    public void clearDebugCacheIfNeeded(ReactInstanceManager instanceManager) {
                                        ^
  :    ReactInstanceManager
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:368: : Ҳ
    static ReactInstanceManager getReactInstanceManager() {
           ^
  :    ReactInstanceManager
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:376: : Ҳ
    public List<NativeModule> createNativeModules(ReactApplicationContext reactApplicationContext) {
                                                  ^
  :    ReactApplicationContext
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:376: : Ҳ
    public List<NativeModule> createNativeModules(ReactApplicationContext reactApplicationContext) {
                ^
  :    NativeModule
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:387: : Ҳ
    public List<Class<? extends JavaScriptModule>> createJSModules() {
                                ^
  :    JavaScriptModule
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:392: : Ҳ
    public List<ViewManager> createViewManagers(ReactApplicationContext reactApplicationContext) {
                                                ^
  :    ReactApplicationContext
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:392: : Ҳ
    public List<ViewManager> createViewManagers(ReactApplicationContext reactApplicationContext) {
                ^
  :    ViewManager
  λ:  CodePush
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\ReactInstanceHolder.java:16: : Ҳ
  ReactInstanceManager getReactInstanceManager();
  ^
  :    ReactInstanceManager
  λ: ӿ ReactInstanceHolder
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:31: : Ҳ
    public WritableMap getBinaryUpdateReport(String appVersion) {
           ^
  :    WritableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:57: : Ҳ
    public WritableMap getRetryStatusReport() {
           ^
  :    WritableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:72: : Ҳ
    public WritableMap getRollbackReport(WritableMap lastFailedPackage) {
                                         ^
  :    WritableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:72: : Ҳ
    public WritableMap getRollbackReport(WritableMap lastFailedPackage) {
           ^
  :    WritableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:79: : Ҳ
    public WritableMap getUpdateReport(WritableMap currentPackage) {
                                       ^
  :    WritableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:79: : Ҳ
    public WritableMap getUpdateReport(WritableMap currentPackage) {
           ^
  :    WritableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:111: : Ҳ
    public void recordStatusReported(ReadableMap statusReport) {
                                     ^
  :    ReadableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:125: : Ҳ
    public void saveStatusReportForRetry(ReadableMap statusReport) {
                                         ^
  :    ReadableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushTelemetryManager.java:143: : Ҳ
    private String getPackageStatusReportIdentifier(ReadableMap updatePackage) {
                                                    ^
  :    ReadableMap
  λ:  CodePushTelemetryManager
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\DownloadProgress.java:3: : com.facebook.react.bridge
import com.facebook.react.bridge.WritableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\DownloadProgress.java:4: : com.facebook.react.bridge
import com.facebook.react.bridge.WritableNativeMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\DownloadProgress.java:15: : Ҳ
    public WritableMap createWritableMap() {
           ^
  :    WritableMap
  λ:  DownloadProgress
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:7: : com.facebook.react.bridge
import com.facebook.react.bridge.Callback;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:8: : com.facebook.react.bridge
import com.facebook.react.bridge.LifecycleEventListener;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:9: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:10: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactContextBaseJavaModule;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:11: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactMethod;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:13: : Ҳ
public class CodePushDialog extends ReactContextBaseJavaModule{
                                    ^
  :  ReactContextBaseJavaModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:15: : Ҳ
    public CodePushDialog(ReactApplicationContext reactContext) {
                          ^
  :    ReactApplicationContext
  λ:  CodePushDialog
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:21: : Ҳ
                           final String button2Text, final Callback successCallback, Callback errorCallback) {
                                                           ^
  :    Callback
  λ:  CodePushDialog
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:21: : Ҳ
                           final String button2Text, final Callback successCallback, Callback errorCallback) {
                                                                                     ^
  :    Callback
  λ:  CodePushDialog
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:52: : Ҳ
                                    String button2Text, final Callback successCallback, Activity currentActivity) {
                                                              ^
  :    Callback
  λ:  CodePushDialog
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:10: : com.facebook.react
import com.facebook.react.ReactApplication;
                         ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:11: : com.facebook.react
import com.facebook.react.ReactInstanceManager;
                         ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:12: : com.facebook.react
import com.facebook.react.ReactRootView;
                         ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:13: : com.facebook.react.bridge
import com.facebook.react.bridge.Arguments;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:14: : com.facebook.react.bridge
import com.facebook.react.bridge.JSBundleLoader;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:15: : com.facebook.react.bridge
import com.facebook.react.bridge.LifecycleEventListener;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:16: : com.facebook.react.bridge
import com.facebook.react.bridge.Promise;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:17: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:18: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactContextBaseJavaModule;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:19: : com.facebook.react.bridge
import com.facebook.react.bridge.ReactMethod;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:20: : com.facebook.react.bridge
import com.facebook.react.bridge.ReadableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:21: : com.facebook.react.bridge
import com.facebook.react.bridge.WritableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:22: : com.facebook.react.modules.core
import com.facebook.react.modules.core.ChoreographerCompat;
                                      ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:23: : com.facebook.react.modules.core
import com.facebook.react.modules.core.DeviceEventManagerModule;
                                      ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:24: : com.facebook.react.modules.core
import com.facebook.react.modules.core.ReactChoreographer;
                                      ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:37: : Ҳ
public class CodePushNativeModule extends ReactContextBaseJavaModule {
                                          ^
  :  ReactContextBaseJavaModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:40: : Ҳ
    private LifecycleEventListener mLifecycleEventListener = null;
            ^
  :    LifecycleEventListener
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:48: : Ҳ
    public CodePushNativeModule(ReactApplicationContext reactContext, CodePush codePush, CodePushUpdateManager codePushUpdateManager, CodePushTelemetryManager codePushTelemetryManager, SettingsManager settingsManager) {
                                ^
  :    ReactApplicationContext
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:101: : Ҳ
    private void setJSBundle(ReactInstanceManager instanceManager, String latestJSBundleFile) throws IllegalAccessException {
                             ^
  :    ReactInstanceManager
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:172: : Ҳ
    private void resetReactRootViews(ReactInstanceManager instanceManager) throws NoSuchFieldException, IllegalAccessException {
                                     ^
  :    ReactInstanceManager
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:192: : Ҳ
    private ReactInstanceManager resolveInstanceManager() throws NoSuchFieldException, IllegalAccessException {
            ^
  :    ReactInstanceManager
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:210: : Ҳ
    public void downloadUpdate(final ReadableMap updatePackage, final boolean notifyProgress, final Promise promise) {
                                     ^
  :    ReadableMap
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:210: : Ҳ
    public void downloadUpdate(final ReadableMap updatePackage, final boolean notifyProgress, final Promise promise) {
                                                                                                    ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:282: : Ҳ
    public void getConfiguration(Promise promise) {
                                 ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:303: : Ҳ
    public void getUpdateMetadata(final int updateState, final Promise promise) {
                                                               ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:371: : Ҳ
    public void getNewStatusReport(final Promise promise) {
                                         ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:428: : Ҳ
    public void installUpdate(final ReadableMap updatePackage, final int installMode, final int minimumBackgroundDuration, final Promise promise) {
                                    ^
  :    ReadableMap
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:428: : Ҳ
    public void installUpdate(final ReadableMap updatePackage, final int installMode, final int minimumBackgroundDuration, final Promise promise) {
                                                                                                                                 ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:516: : Ҳ
    public void isFailedUpdate(String packageHash, Promise promise) {
                                                   ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:526: : Ҳ
    public void getLatestRollbackInfo(Promise promise) {
                                      ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:541: : Ҳ
    public void setLatestRollbackInfo(String packageHash, Promise promise) {
                                                          ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:552: : Ҳ
    public void isFirstRun(String packageHash, Promise promise) {
                                               ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:566: : Ҳ
    public void notifyApplicationReady(Promise promise) {
                                       ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:577: : Ҳ
    public void recordStatusReported(ReadableMap statusReport) {
                                     ^
  :    ReadableMap
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:586: : Ҳ
    public void restartApp(boolean onlyIfUpdateIsPending, Promise promise) {
                                                          ^
  :    Promise
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:604: : Ҳ
    public void saveStatusReportForRetry(ReadableMap statusReport) {
                                         ^
  :    ReadableMap
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:5: : com.facebook.react.bridge
import com.facebook.react.bridge.Arguments;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:6: : com.facebook.react.bridge
import com.facebook.react.bridge.NoSuchKeyException;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:7: : com.facebook.react.bridge
import com.facebook.react.bridge.ReadableArray;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:8: : com.facebook.react.bridge
import com.facebook.react.bridge.ReadableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:9: : com.facebook.react.bridge
import com.facebook.react.bridge.ReadableMapKeySetIterator;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:10: : com.facebook.react.bridge
import com.facebook.react.bridge.ReadableType;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:11: : com.facebook.react.bridge
import com.facebook.react.bridge.WritableArray;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:12: : com.facebook.react.bridge
import com.facebook.react.bridge.WritableMap;
                                ^
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:31: : Ҳ
    public static WritableArray convertJsonArrayToWritable(JSONArray jsonArr) {
                  ^
  :    WritableArray
  λ:  CodePushUtils
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:63: : Ҳ
    public static WritableMap convertJsonObjectToWritable(JSONObject jsonObj) {
                  ^
  :    WritableMap
  λ:  CodePushUtils
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:99: : Ҳ
    public static JSONArray convertReadableToJsonArray(ReadableArray arr) {
                                                       ^
  :    ReadableArray
  λ:  CodePushUtils
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:138: : Ҳ
    public static JSONObject convertReadableToJsonObject(ReadableMap map) {
                                                         ^
  :    ReadableMap
  λ:  CodePushUtils
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushUtils.java:224: : Ҳ
    public static String tryGetString(ReadableMap map, String key) {
                                      ^
  :    ReadableMap
  λ:  CodePushUtils
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushDialog.java:19: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushDialog
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:209: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:281: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:302: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:370: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:427: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:515: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
D:\gitee\Knowledge\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:525: : Ҳ
    @ReactMethod
     ^
  :    ReactMethod
  λ:  CodePushNativeModule
100
:react-native-code-push:compileReleaseJavaWithJavac (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 0.113 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-code-push:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by JulioCVaz** [comment]
Same here

**Comment by lucianolopezz** [comment]
Same here, after update compileSdkVersion to 31

**Comment by dann95** [comment]
> Same here, after update compileSdkVersion to 31

+1

**Comment by dann95** [comment]
@lucianolopezz have you found any workaround?

**Comment by lucianolopezz** [comment]
> @lucianolopezz have you found any workaround?

Upgrade react-native to 0.67.5

**Comment by FernandoLooplan** [comment]
Same here. 
"react-native-code-push": "^8.1.1"
"react-native": "^0.73.0"

**Comment by DmitriyKirakosyan** [comment]
@FernandoLooplan please try updating react-native-code-push to the latest version and reproduce the issue on a newly created react-native app.
