### ISSUE TITLE
appcenter codepush, but cli not found

### ISSUE THREAD

**Issue by vincentsartoko** [microsoft/react-native-code-push#2776]
1. Run this command:
`appcenter codepush release-react -a xxx/yyy -d Production`

2. Error
`Error: Cannot find module 'C:\Users\xxx\Desktop\Lahelu\Codebase\Client\node_modules\react-native\local-cli\cli.js'`

Has anyone ever encountered such issue?

**Comment by Rajeshmy** [comment]
Am facing the same after upgrading RN version from 0.74.2 to 0.76.1 (Works well with 0.74.2)

 error Details below:-
node:internal/modules/cjs/loader:1148
  throw err;
  ^
 
Error: Cannot find module '/Users/xxxxx/node_modules/react-native/local-cli/cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 
Node.js v20.14.0
[Error]  "react-native bundle" command exited with code 1.

version:-  "react-native-code-push": "^8.3.1"/"9.0.0" and others as well,


Requesting Help here !!

**Comment by TuanTran-Tsk** [comment]
> Hello, and thank you for reaching out! I believe the issue is that since React Native 0.76, a new architecture is enabled by default, which isn't currently supported by react-native-code-push.
> 
> Could you please try disabling this new architecture following this [guide](https://reactnative.dev/architecture/landing-page)? Let us know if this resolves the issue. Thank you!

Does CodePush Team have any plan to support New Architecture?

**Comment by DordeDimitrijev** [comment]
RNCP won't support NA please check https://github.com/microsoft/react-native-code-push/issues/2774#issuecomment-2507636494 for reference.

**Comment by DordeDimitrijev** [comment]
@TuanTran-Tsk  You can try out  approach mentioned in this comment to use new architecture https://github.com/microsoft/react-native-code-push/issues/2781#issuecomment-2519480160
