### ISSUE TITLE
undefined is not a function (evaluating 'this._lazyCallableModules[name]()') 

### ISSUE THREAD

**Issue by yogeshchoudhary147** [Microsoft/react-native-code-push#1493]
**Initial Error:**
Error: ENOENT: no such file or directory, open '/Users/apple/Documents/.../android/app/build/intermediates/assets/debug/CodePushHash'

**react-native-code-push 5.3.5
RN 0.55.4
Gradle 3.2.1**

**Solution tried:**
Then I tried solution mentioned [here](https://github.com/Microsoft/react-native-code-push/issues/1427) of modifying "project.ext.react" in app/build,gradle. Now, I am perfectly able to run **debug** app but when I am running **release** app on android emulator then I am getting below mentioned errors on 2nd app launch. 

[ERROR] [Global-Fatal] undefined is not a function (evaluating 'this._lazyCallableModulesname') value@/data/user/0/com.udaan.android/files/CodePush/452bbaf8f06ae3aeaa26826d4cad0ce04ab863c2fc3ffd31de75f435210c9ac6/CodePush/index.android.bundle:30:2504

[ERROR] [Global-Fatal] undefined is not an object (evaluating 'customBubblingEventTypes[topLevelType]') extractEvents@/data/user/0/com.udaan.android/files/CodePush/452bbaf8f06ae3aeaa26826d4cad0ce04ab863c2fc3ffd31de75f435210c9ac6/CodePush/index.android.bundle:121:17304

Any idea what's this related to?

I did this to create js bundle:
_react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/_

**Comment by yuri-kulikov** [comment]
Hey @yogeshchoudhary147,
Thanks for reporting!

It's hard to say how `react-native 0.55` will work with `gradle 3.2` with this workaround. We need some time to check this configuration.
Maybe you can provide us a simple reproducible demo so we could test it directly?

**Comment by yuri-kulikov** [comment]
Hi @yogeshchoudhary147,
Sorry for the delay!

I've created a project with `react-native-code-push 5.3.5`, `RN 0.55.4` and `Gradle 3.2.1` (with  `project.ext.react` workaround) and everything works fine. 

You can check my demo project here: [Issue1493H.zip](https://github.com/Microsoft/react-native-code-push/files/2740652/Issue1493H.zip)

#### Steps to run:
- Unzip the project
- `npm install`
- Set your signingConfigs in `/android/app/build.gradle` file
- Run the app from Android Studio

You can check this demo and share the results with me.

**Comment by yogeshchoudhary147** [comment]
Hi @yuri-kulikov 

Thanks for your reply. I missed to update here but the error has disappeared as of now.
