### ISSUE TITLE
code-push does not compile on android on 0.620rc

### ISSUE THREAD

**Issue by osdnk** [microsoft/react-native-code-push#1772]
### Steps to Reproduce
1. set up project
2. compile

### Expected Behavior
Should compile smoothly

### Actual Behavior
What actually happens?
```
/Users/osdnk/work/rainbow/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java:157: error: cannot find symbol
                isLiveReloadEnabled = devInternalSettings.isReloadOnJSChangeEnabled();
```

Happens after this commit https://github.com/facebook/react-native/commit/478df155e70a4ce30219adcac6f0801c4e4d10ec#diff-2fc30127a6c6568653505923bbd3bdbb

Hopefully no need to repro :)

### Environment

System:
    OS: macOS Mojave 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 41.38 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 22, 23, 26, 28, 29
      Build Tools: 22.0.1, 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 3.0.4 => 3.0.4
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0-rc.1 => 0.62.0-rc.1
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by osdnk** [comment]
I make a fork on my GH where it works  ¯\_(ツ)_/¯

**Comment by owinter86** [comment]
This issue is live reload no longer exists as it was removed as part of the fast refresh update.

So the conditional found here 

https://github.com/microsoft/react-native-code-push/blob/6ffa5ff525430eb1507e37587b0af82550965c4b/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L153

will cause the build failures and can be removed, I suspect the error will still exists if you delete your android build, as this is still present on the unreleased master branch.

**Comment by alexandergoncharov** [comment]
Hi all,
Thanks for reporting!

I reproduced issue on `react-native@0.62.0-rc.1` version. We will investigate it. Thanks!

**Comment by bang88** [comment]
Any update on this. 

Thank you

**Comment by wong2** [comment]
any updates?

**Comment by ryanlntn** [comment]
Having difficulty with upgrading to 0.62 but getting a different error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-code-push.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-code-push:
          - None of the consumable configurations have attributes.
```

The project was resolving with react-native 0.61.5

**Comment by JoaoPauloCMarra** [comment]
still happens

**Comment by marf** [comment]
Hello, we have 

> Having difficulty with upgrading to 0.62 but getting a different error:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:mergeDebugAssets'.
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve project :react-native-code-push.
>      Required by:
>          project :app
>       > Unable to find a matching configuration of project :react-native-code-push:
>           - None of the consumable configurations have attributes.
> ```
> 
> The project was resolving with react-native 0.61.5

We have this problem too!
Any fixes?

**Comment by tiendn** [comment]
Same here,
The project was resolving with react-native 0.62.0, just init today.

**Comment by mftaher** [comment]
same

**Comment by namxam** [comment]
Looking at `DevInternalSettings` code, I guess we should replace it for 0.62 with `devInternalSettings.isHotModuleReplacementEnabled()`.

**Comment by hengki01** [comment]
Any update ? still not working with RN 0.62.0, just works fine with RN 0.61.5

**Comment by ajiehatajie** [comment]
same here , still not working with RN 0.62.0,

**Comment by alexlevy0** [comment]
same here :(

**Comment by tiendn** [comment]
Here is an new fresh project. I tried to build with code-push, but it always failed.
https://github.com/tiendn/covid

**Comment by tr3v3r** [comment]
@tiendn After react-native-code-push update to `6.2.0` problem was disappeared.

**Comment by tiendn** [comment]
I tried with https://github.com/microsoft/react-native-code-push/issues/1831#issuecomment-608996707. It works
